# Veil-Miner custom miner package for HiveOS
CUSTOM_NAME=veilminer
CUSTOM_VERSION=1.1.3
CUSTOM_LOG_BASENAME=/var/log/miner/custom/veilminer
CUSTOM_CONFIG_FILENAME=/hive/miners/custom/veilminer/veilminer.conf
